# Generated by Django 2.2 on 2020-01-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='الإسم')),
                ('last_name', models.CharField(max_length=255, verbose_name='اللقب')),
                ('picture', models.ImageField(upload_to='children/pictures', verbose_name='الصورة')),
                ('sex', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('m', 'ذكر'), ('f', 'أنثى')], max_length=1, null=True, verbose_name='الجنس')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='المستوى الدراسي')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاريخ الإزدياد')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='رقم الهاتف')),
                ('village', models.CharField(blank=True, max_length=155, null=True, verbose_name='الدوار')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الوزن')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='القامة')),
                ('bed_position', models.CharField(blank=True, max_length=15, null=True, verbose_name='تموضع السرير')),
                ('shoo_size', models.CharField(blank=True, max_length=8, null=True, verbose_name='مقاس الحذاء')),
                ('vision', models.CharField(blank=True, max_length=55, null=True, verbose_name='الرؤية')),
                ('orphan_side', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('mother', 'الأم'), ('father', 'الأب'), ('both', 'الأم و الأب')], max_length=10, null=True, verbose_name='اليتم')),
                ('chronic_disease', models.CharField(blank=True, max_length=55, null=True, verbose_name='مرض مزمن')),
                ('hobby', models.CharField(blank=True, max_length=25, null=True, verbose_name='الهواية')),
                ('status', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'وافد'), ('left', 'مغادر'), ('dropped', 'منقطع')], max_length=10, null=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'طفل',
                'verbose_name_plural': 'أطفال',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
