# Generated by Django 2.2 on 2020-01-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='full_name',
            field=models.CharField(default=2, max_length=255, verbose_name='الإسم الكامل'),
            preserve_default=False,
        ),
    ]
