# Generated by Django 2.2 on 2020-01-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_child_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الإسم الكامل'),
        ),
    ]
