# Generated by Django 2.2 on 2020-01-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0003_auto_20200116_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='picture',
            field=models.ImageField(upload_to='images/children', verbose_name='الصورة'),
        ),
    ]
