# Generated by Django 2.2 on 2020-01-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0004_auto_20200117_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/children', verbose_name='الصورة'),
        ),
    ]
