# Generated by Django 2.2 on 2020-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0005_auto_20200129_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='subscription_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الإنخراط'),
        ),
    ]
