# Generated by Django 2.2 on 2020-02-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0006_child_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='subscription_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='رقم الإنخراط'),
        ),
    ]
