# Generated by Django 2.2 on 2020-10-26 22:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('orphanage', '0007_auto_20200229_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'المستوى الدراسي',
                'verbose_name_plural': 'المستويات الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/guardians', verbose_name='الصورة')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='رقم الهاتف')),
                ('status', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('', '')], max_length=10, null=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'الكافل',
                'verbose_name_plural': 'الكفلاء',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='السنة')),
            ],
            options={
                'verbose_name': 'السنة الدراسية',
                'verbose_name_plural': 'السنوات الدراسية',
            },
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'طفل', 'verbose_name_plural': 'أطفال'},
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('code', models.CharField(max_length=10, verbose_name='الرقم')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.Grade')),
            ],
            options={
                'verbose_name': 'المادة الدراسية',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1_mark', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='نقطة الدورة الأولى')),
                ('s2_mark', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='نقطة الدورة الثانية')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.Child')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.Grade')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.Year')),
            ],
            options={
                'verbose_name': 'الملف الدراسي',
                'verbose_name_plural': 'الملفات الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='النقطة')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.Registration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.Subject')),
            ],
            options={
                'verbose_name': 'النقطة',
                'verbose_name_plural': 'النقط',
            },
        ),
    ]
