# Generated by Django 2.2 on 2020-10-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0008_auto_20201026_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='رقم الإنخراط')),
                ('first_name', models.CharField(max_length=255, verbose_name='الإسم')),
                ('last_name', models.CharField(max_length=255, verbose_name='اللقب')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الإسم الكامل')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/students', verbose_name='الصورة')),
                ('sex', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('m', 'ذكر'), ('f', 'أنثى')], max_length=1, null=True, verbose_name='الجنس')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='المستوى الدراسي')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاريخ الإزدياد')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='رقم الهاتف')),
                ('village', models.CharField(blank=True, max_length=155, null=True, verbose_name='الدوار')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الوزن')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='القامة')),
                ('bed_position', models.CharField(blank=True, max_length=15, null=True, verbose_name='تموضع السرير')),
                ('shoo_size', models.CharField(blank=True, max_length=8, null=True, verbose_name='مقاس الحذاء')),
                ('vision', models.CharField(blank=True, max_length=55, null=True, verbose_name='الرؤية')),
                ('orphan_side', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('mother', 'الأم'), ('father', 'الأب'), ('both', 'الأم و الأب')], max_length=10, null=True, verbose_name='اليتم')),
                ('chronic_disease', models.CharField(blank=True, max_length=55, null=True, verbose_name='مرض مزمن')),
                ('hobby', models.CharField(blank=True, max_length=25, null=True, verbose_name='الهواية')),
                ('status', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'وافد'), ('left', 'مغادر'), ('dropped', 'منقطع')], max_length=10, null=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'طفل',
                'verbose_name_plural': 'أطفال',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('-year',), 'verbose_name': 'السنة الدراسية', 'verbose_name_plural': 'السنوات الدراسية'},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='child',
        ),
        migrations.AlterField(
            model_name='grade',
            name='title',
            field=models.CharField(max_length=255, verbose_name='المستوى'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orphanage.Student'),
            preserve_default=False,
        ),
    ]
