# Generated by Django 2.2 on 2020-11-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0010_auto_20201101_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='رقم الإنخراط')),
                ('first_name', models.CharField(max_length=255, verbose_name='الإسم')),
                ('last_name', models.CharField(max_length=255, verbose_name='اللقب')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الإسم الكامل')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/students', verbose_name='الصورة')),
                ('sex', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('m', 'ذكر'), ('f', 'أنثى')], max_length=1, null=True, verbose_name='الجنس')),
                ('grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='المستوى الدراسي')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاريخ الإزدياد')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='رقم الهاتف')),
                ('village', models.CharField(blank=True, max_length=155, null=True, verbose_name='الدوار')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الوزن')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='القامة')),
                ('bed_position', models.CharField(blank=True, max_length=15, null=True, verbose_name='تموضع السرير')),
                ('shoo_size', models.CharField(blank=True, max_length=8, null=True, verbose_name='مقاس الحذاء')),
                ('vision', models.CharField(blank=True, max_length=55, null=True, verbose_name='الرؤية')),
                ('orphan_side', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('mother', 'الأم'), ('father', 'الأب'), ('both', 'الأم و الأب')], max_length=10, null=True, verbose_name='اليتم')),
                ('chronic_disease', models.CharField(blank=True, max_length=55, null=True, verbose_name='مرض مزمن')),
                ('hobby', models.CharField(blank=True, max_length=25, null=True, verbose_name='الهواية')),
                ('status', models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'مستجد'), ('left', 'مغادر'), ('dropped', 'منقطع')], max_length=10, null=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'طفل',
                'verbose_name_plural': 'أطفال',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('child',), 'verbose_name': 'تلميذ', 'verbose_name_plural': 'تلاميذ'},
        ),
        migrations.RemoveField(
            model_name='mark',
            name='registration',
        ),
        migrations.AddField(
            model_name='grade',
            name='year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='orphanage.Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orphanage.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='s1_mark',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='نقطة الدورة الأولى'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='s2_mark',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='نقطة الدورة الثانية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_mark',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='معدل السنة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardian',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('pending', 'في إنتظار الموافقة'), ('accepted', 'طلب مقبول'), ('accepted', 'طلب مرفوض')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'مستجد'), ('left', 'مغادر'), ('dropped', 'منقطع')], max_length=10, null=True, verbose_name='الحالة'),
        ),
        migrations.DeleteModel(
            name='Registration',
        )
    ]
