# Generated by Django 2.2 on 2020-11-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0011_auto_20201112_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orphanage.Child'),
            preserve_default=False,
        ),
    ]
