# Generated by Django 2.2 on 2020-11-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0012_student_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bed_position',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='chronic_disease',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='height',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='orphan_side',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoo_size',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='village',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weight',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orphanage.Grade'),
            preserve_default=False,
        ),
    ]
