# Generated by Django 2.2 on 2020-11-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0013_auto_20201113_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'مستجد'), ('passed', 'متأهل'), ('repeated', 'مكرر')], max_length=10, null=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.Grade', verbose_name='المستوى الدراسي'),
        ),
    ]
