# Generated by Django 2.2 on 2020-11-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0014_auto_20201113_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='المستوى الدراسي'),
        ),
    ]
