# Generated by Django 2.2 on 2020-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0015_child_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='المستوى'),
            preserve_default=False,
        ),
    ]
