# Generated by Django 2.2 on 2020-11-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0016_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s1_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='نقطة الدورة الأولى'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s2_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='نقطة الدورة الثانية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'مستجد'), ('passed', 'متأهل'), ('repeated', 'مكرر')], default='passed', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل السنة'),
        ),
    ]
