# Generated by Django 2.2 on 2020-11-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0017_auto_20201114_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['level'], 'verbose_name': 'المستوى الدراسي', 'verbose_name_plural': 'المستويات الدراسية'},
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'وافد'), ('left', 'مغادر'), ('dropped', 'منقطع')], default='', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orphanage.Child', verbose_name='الطفل'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('level', 'year')},
        ),
    ]
