# Generated by Django 2.2 on 2020-12-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0018_auto_20201128_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coeff',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='المعامل'),
        ),
    ]
