# Generated by Django 2.2 on 2021-01-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0019_subject_coeff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s1_decision',
            field=models.CharField(choices=[('', 'إختر من القائمة'), ('F', 'راسب'), ('C', 'مقبول'), ('B', 'مستحسن'), ('A', 'حسن'), ('A+', 'حسن جدا')], default='', max_length=2, verbose_name='ميزة الدورة الأولى'),
        ),
        migrations.AddField(
            model_name='student',
            name='s2_decision',
            field=models.CharField(choices=[('', 'إختر من القائمة'), ('F', 'راسب'), ('C', 'مقبول'), ('B', 'مستحسن'), ('A', 'حسن'), ('A+', 'حسن جدا')], default='', max_length=2, verbose_name='ميزة الدورة الثانية'),
        ),
        migrations.AddField(
            model_name='student',
            name='year_decision',
            field=models.CharField(choices=[('', 'إختر من القائمة'), ('F', 'راسب'), ('C', 'مقبول'), ('B', 'مستحسن'), ('A', 'حسن'), ('A+', 'حسن جدا')], default='', max_length=2, verbose_name='ميزة السنة'),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'وافد'), ('qualified', 'متأهل'), ('left', 'مغادر'), ('dropped', 'منقطع')], default='', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'إختر من القائمة'), ('new', 'وافد'), ('qualified', 'متأهل'), ('left', 'مغادر'), ('dropped', 'منقطع')], default='passed', max_length=10, verbose_name='الحالة'),
        ),
    ]
